apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
type: Opaque
stringData:
  # Cloudflare Tunnel token
  tunnel-token: "eyJhIjoiYTM1ZmJhNzU1OTc5NmJmZTAwZDBiNGJiMzVlODhjZDEiLCJ0IjoiNmVjZjQzNjgtNWI0Yi00YTk1LWE4MzktZWNlZGE5NTE3ODc3IiwicyI6Ik1XWTROR1k0TlRrdE1qYzVPQzAwTjJGbExUbG1OR1V0TWpKaU0yTXpPRFJoWlRZMiJ9"