apiVersion: ENC[AES256_GCM,data:9Vc=,iv:P6XvdExIuKFGLaMpxwDRI6LgTttoKyAH51YTB/e9S/M=,tag:HXDDf51AQydNsxE5p8cwvg==,type:str]
kind: ENC[AES256_GCM,data:Unmmorbb,iv:Yc992Usoa5JeeHoqTmTIE0vXYWkwHyIgtbb6PM1bcH0=,tag:bvSnhVkg+r4YnT8zWWQROg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8Mhp/KRjatKUJcM6O34dGLG2g0RDSsA=,iv:RaTOvBwJweAZEWsyyiunVHNWGOi3HzjUEKfQ91O4FZY=,tag:5Nb+jvdYR4VYBaKp7y01gw==,type:str]
    namespace: ENC[AES256_GCM,data:ZN5tH+WmTyPhpw==,iv:9mJdGzKcUzwgTN3UPB/WntgDar4DkeD38wQ5jFrxkbk=,tag:GiM0ts/TrLofPkBfd/r7uA==,type:str] #ENC[AES256_GCM,data:/YHQAF/77ITybQ7p7LgFwlEFykrKw5L5v3Ztyp3u8UoRVTs0WsY5zAenTOAcyOvqPWoTC+0TVRzXioOdFvu1gV3diZb9VMAfVZQOhPsG7Q==,iv:W7mIAdJGogCeSDdTc7RekilkLOUGd1qIeTe6pJLbJU4=,tag:ff6gq8bXdA8b0bR/9KNIjg==,type:comment]
type: ENC[AES256_GCM,data:AOqPlcIa,iv:XYhOPkIML4K+Iv2sfRGaZLHxArwOtHNjYG8fotgx87o=,tag:sjyIZzs+ABDVN7RRSZ2tDw==,type:str]
stringData:
    tunnel-token: ENC[AES256_GCM,data:Fs1VNA6iIw+VAEEAmRrlq1sPHOVBmQFLD7IrSQyC1yjIn9RIHxD6pf9wbcsc68xWBhXh4Yg5OM/TqTmkd2V6WPE0kSsDWowhU3FkQYC96KPF3HTvwYnOrQ71VOV1GA+6GN9Et9A090RTqgCE9oOaQK0qdevEV6OFCj40vtHVm01aJ8nYd7PiJ6QDtjbLk8yUPtZg9uxJzzZ0zoOTQtts0Dfq4iyoUFLta+WT3pWY3jc745PiWZnCOQ==,iv:0ADpFTIv5zSXmwk0G0FzuJhWI1z57A4+9BdiV7zEu5M=,tag:ocKNltOypzbdYOtg2ADXdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOGZRZFRzRHduQ1VEcUlq
            UDJhV1N1TzM3K2Y2NEZCeWhvbStjdnV3VWxvCnEydUMxSlVZemdpNHVRaFZaZnZz
            UDh4SWlQUUN3aURTTmZTTi82c2JIZk0KLS0tIGNmTHRMeVJmS0lSSFJ2enc4OWFX
            VXorcGVJdlBPN2NUK0lHZGdtWjB3L1EK1Lav+IHSQwq6jX7CaC7kU0R+keMmE+Bs
            GoTz9MBgl0B3j3MG+h/xJsPJQwnPH7ddJxVquYhwiYFIgka9FPgNdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1835kc484s2lckjuthk4kldjjcywjd8qxnuywnfayxd85hm6hpu3sjhqdew
    lastmodified: "2026-05-19T02:15:48Z"
    mac: ENC[AES256_GCM,data:uCNX+SUBnUyTaPc8VkkMZGaa5vGLY7IBLOepMYRMWpU5lMsEeIXFIA+6mrnYFvatvLupFcspt6z9CFzdYJosMmsi81WaABqOjf/nYskuKYeCV+wU3iqD8I2Y6tE6qzPv2S+7PvC+s6C6ROhfmUH9nQbFBAMAB1duc8Ur9jB9Dk8=,iv:W7GX5lMuWXSRElkhlERKi8qgHPZudbAU75eKJpwa8K8=,tag:Re2rIMTrzZl5pd3nF6R0MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
