hello: ENC[AES256_GCM,data:qOUT9oXMOqmmW6RPg1BrOCJ/YtjbivToRBkQCK3LG93kHtaKfdB9v+FawLffPw==,iv:BoaX9A5+tl8gHdBBlSHLpGjOv1Coz7guWXkCutHlyV0=,tag:rEf11hA6ysbDNURsdsAXUw==,type:str]
apiVersion: ENC[AES256_GCM,data:oeA=,iv:QHiPRV3LjmmG4MaCP/KeaBULioPPMkEKubjqd2GhKfw=,tag:9oNmEwoUu65xnYrrnU00QQ==,type:str]
kind: ENC[AES256_GCM,data:ODcxxep0,iv:yaLItg6/uOwx3WyfFpn3TePb8KMAszWQshH11xqpk8o=,tag:HfweAzi4sK7NWVeql/QEZg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0jNbDAEx9Tz9BPZciz0zFHIrNZc2P+g=,iv:9Y6XA9IMWF0PJsxXttinzHZk0/QaEc/lEKG2nCwZFKM=,tag:sixswftNC/VYGLtY9tnTmg==,type:str]
    namespace: ENC[AES256_GCM,data:Y5aTK8QPsQ==,iv:TscK36hJh+mxXZImJkkwf04QsPoaKgtGNHYcqDZDrpo=,tag:ec1lknSIOtpvhTtm3kWfRw==,type:str]
type: ENC[AES256_GCM,data:VVsyNvgh,iv:SaK6vX2jwNpCIgiDbtjG5wJMtt4F52arlOYznJRwPbM=,tag:owpptKBe9QhkWP1rfVPzlg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:EKTMEqRFSYyBwwS6hGFe13Vo5fJrqwR7wdQ5inp4tu5XqBmMYI9XL6Z2aw3ycXsQVDmYBYx7blYk1S/ge6RyU3nHEfp7LmixEUdDQ2p2PAlt1c2vtowW67yuv3q3hbUW/PKIN+7uyFjx7PRNoBrnGdUhpw5rsvux2EGKLUbETclQZGOgXi7vsnfeDpoq/1IIO16nJhv4hpTIJV5W2pMCl9LAdLwwGBsElHhwu+4mv9X58YgOOqKkJA==,iv:Zit3mS+mOIKg4TTb+txu6yoiVyay4h9GXNqXIWRy9GU=,tag:dxxVcXyBwt8CmWKt6QkBIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRDRnZDltWjZ5Y0xZMHNO
            VWNvRkgvNlA4MjRzTmNuQjE0SkcwQWc2RFRZClBpUjQwTGtsSW1pRG9KZ1k3eXFK
            K2pScllOT0hkTGZlVUh6Q3FzMjVDT2cKLS0tIEp3cGJlbzJFcmVMa0NVTDB5bjIw
            YjhqTDhJV2tRUVFwY0tuWmdXVjJVV3MKD9SGNeU58hCKZL8mGG3JjaboDqjnBLEN
            Sdg72AnkC6LD8osBAOKDloQn4tRX23D9RSs6X8+QkF5XpGEVMQPDqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17emkucqwhve70tcchnlu830qjq60t72t2anq7ur3c93w36ywvc8sz69n8z
    lastmodified: "2026-05-19T00:27:55Z"
    mac: ENC[AES256_GCM,data:5bzPo5uZIBHLRllJgbYB7Bohgl1RAAkLG1wmgbnnWWUzqxGWZVBIzqXtW3DPReKN/dXd38h5kHHJAo4UYSqAqfPGDIeGHBP7Fvaw22640GuRvp8BhUDO2kiLN6pYGIKXA5O5eTLnFC/Y0HoVy6+TCUpMee+bJ91qXyUNZ+PpPz4=,iv:qmEqwrgd8DCTv7e3gjGYBnMCiwjD6NsUu5/Q5Th2rkI=,tag:VwqAXEEfUwV39HAV4J/xSQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
