apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:1E6iJPb2PHkexjCcbfEHhU/SPp0BCKeqvJgt3Exm3bnuAObuyera+qbJxgpB20NxJG3Bh+hK793/KFToz9lUXIcTzEps110nfkhksX+4Q6Ls7qG4TOIROM8iGE+rmQzUUlOGHosWJ3uyNJKTYqKw+fTb3ukj6IUdbx80L3RjuxKlKvvEdMIHEnEfCd96hk7/YTBPvtvkF6K/IkO+vvIg2wkcAa41dAgcvqvdR4GwL0PNgyXCB6azgw==,iv:eX/CAZiwG3NYUJvUPoYghY6bvAOvIMXdyyhtjyxC9eU=,tag:IgpY8XyKMBoqMygsZ9J/Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVUdDdnh0U3B3MWZRQ2tw
            M2ZEYk54eWpaWjhBNWpESS9OOUxzMmQrVHlnCml1VG1NSTBEY28xNnlNNWxpMXJI
            OURYUTEvZWN4K1pLcXJmMWd6ZnVQc2cKLS0tIG9nS2FVamJiTUhBdUhCdnZ3Wnda
            aWFzWGdQVDZES2g4UkpHcUpCRDRBM2MKADV3xvPhhx58uCqTLO7aSryIEMxoEDrU
            s5RTO/YsbA1ckXUkJzkefdr356ZjX4e7nT9HQANaqiLiwvgnGBQd5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17lvlgec9840v9ymlfltd2tyve4muvz40ag32jj6p2vx2mhu3y3nq5jzl2m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T04:39:28Z"
    mac: ENC[AES256_GCM,data:ksysM4IbS6rViwPIGsz//32HPVaseA61mB/xjz5VFoxoTQqQoZ0CM3mX+ksgbbPKWTsFAF7mCdV8kBfS8hAO1oGO6nbpBFc+PsuKHqDfGaVuw6mRzW+sjOkIC88iNDR3PPzUX4HMfBF9ZFnBbAYImFyr1LacYDUAaQSYY+dJFVE=,iv:RzmZ7td+IqqoKbQRagkVoGQtsA7vauKGMNkIjglYx+o=,tag:07iRfVsdajTR4XJt0/1zuQ==,type:str]
    version: 3.13.1
